---
- assert:
    that: openshift_deployment_type in known_openshift_deployment_types

- name: Ensure libselinux-python is installed
  yum:
    pkg: libselinux-python
    state: present

- name: Create any additional repos that are defined
  template:
    src: yum_repo.j2
    dest: /etc/yum.repos.d/openshift_additional.repo
  when: openshift_additional_repos | length > 0

- name: Remove the additional repos if no longer defined
  file:
    dest: /etc/yum.repos.d/openshift_additional.repo
    state: absent
  when: openshift_additional_repos | length == 0

- include: default.yaml
  when: openshift_deployment_type != online

- include: online.yaml
  when: openshift_deployment_type == online